[template]
cargo_generate_version = ">=0.9.0"
description = "A Pico project template with Embassy"

[hooks]
pre = ["cargo-generate/prehook.rhai"]


[placeholders.defmt]
type = "bool"
prompt = "Enable defmt logging (requires a debug probe)?"
default = false
